spring:
  profiles:
    default: dev

# ==========================================
# CONFIGURACIÓN GLOBAL (Aplica a Dev y Prod)
# ==========================================
application:
  security:
    jwt:
      # Clave secreta para firmar los tokens (Base64)
      # Se lee de la variable de entorno JWT_SECRET_KEY. Si no existe, usa el valor por defecto.
      secret-key: ${JWT_SECRET_KEY:rN8skz5ksunBA2xbiWLw7ir+wrBou6Zx8HppAlkJUh0=}
      expiration: 86400000 # 24 horas

---

spring:
  config:
    activate:
      on-profile: dev # Configuración para el perfil 'dev'

  datasource:
    url: jdbc:postgresql://localhost:5432/cudeca_db
    username: cudeca_user
    password: password_seguro
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate # Valida que el esquema de BD coincida con las entidades JPA
    show-sql: true # Muestra SQL en consola
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  mail:
    host: localhost
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls.enable: false

  springdoc:
    swagger-ui:
      enabled: true

server:
  port: ${SERVER_PORT:8080}

---
# ==========================================
# PERFIL PROD (Nube - Render/Neon)
# ==========================================
spring:
  config:
    activate:
      on-profile: prod # Configuración para el perfil 'prod' (despliegue)

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  mail:
    host: localhost
    port: 1025
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          auth: false
          starttls.enable: false

  springdoc:
    swagger-ui:
      enabled: false

logging:
  file:
    name: logs/cudeca-backend.log
  level:
    root: WARN
    org.springframework: WARN
    org.hibernate.SQL: WARN
    com.cudeca: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"

application:
  security:
    jwt:
      # En producción, esta clave DEBE ser establecida a través de la variable de entorno JWT_SECRET_KEY.
      secret-key: ${JWT_SECRET_KEY:B4-CLAVE-SECRETA-SUPER-LARGA-Y-COMPLEJA-DE-SAPOSOFT}
      expiration: 86400000 # 24 horas en milisegundos

server:
  port: ${PORT:8080}
